### ISSUE TITLE
alsactl restore coredumps with version 1.2.5

### ISSUE THREAD

**Issue by mabod** [alsa-project/alsa-utils#93]
This morning I received the alsa update to 1.2.5 on my arch system. Now during every boot alsactl restore crashes:

```
10# alsactl restore
alsactl: load_state:1635: Cannot open /var/lib/alsa/asound.state for reading: No such file or directory
alsa-lib ucm_subs.c:252:(rval_lookup_main) Lookups are supported in v4+ syntax
alsa-lib parser.c:242:(error_node) UCM is not supported for this HDA model (HDA ATI HDMI at 0xfcda0000 irq 191)
alsa-lib main.c:1402:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -6
Found hardware: "HDA-Intel" "ATI R6xx HDMI" "HDA:1002aa01,00aa0100,00100700" "0x1002" "0xab38"
Hardware is initialized using a generic method
alsa-lib ucm_subs.c:252:(rval_lookup_main) Lookups are supported in v4+ syntax
alsa-lib parser.c:242:(error_node) UCM is not supported for this HDA model (HD-Audio Generic at 0xfcc00000 irq 192)
alsa-lib main.c:1402:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -6
Found hardware: "HDA-Intel" "Realtek ALC1220" "HDA:10ec1220,1458a0c3,00100101" "0x1458" "0xa0c3"
Hardware is initialized using a generic method
[1]    9545 segmentation fault (core dumped)  alsactl restore
```

and

```
Jun 06 08:17:12 rakete systemd-coredump[9547]: [🡕] Process 9545 (alsactl) of user 0 dumped core.
                                               
                                               Stack trace of thread 9545:
                                               #0  0x00007ff3598f9557 snd_config_delete (libasound.so.2 + 0x31557)
                                               #1  0x000056483cd06038 n/a (alsactl + 0xc038)
                                               #2  0x000056483cd00706 n/a (alsactl + 0x6706)
                                               #3  0x00007ff359702b25 __libc_start_main (libc.so.6 + 0x27b25)
                                               #4  0x000056483cd00a5e n/a (alsactl + 0x6a5e)
```

Downgrading to alsa-utils 1.2.4-2 fixes it:

```
9# alsactl restore
alsactl: load_state:1683: Cannot open /var/lib/alsa/asound.state for reading: No such file or directory
alsa-lib ucm_subs.c:252:(rval_lookup_main) Lookups are supported in v4+ syntax
alsa-lib parser.c:242:(error_node) UCM is not supported for this HDA model (HDA ATI HDMI at 0xfcda0000 irq 191)
alsa-lib main.c:1402:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -6
Found hardware: "HDA-Intel" "ATI R6xx HDMI" "HDA:1002aa01,00aa0100,00100700" "0x1002" "0xab38"
Hardware is initialized using a generic method
alsa-lib ucm_subs.c:252:(rval_lookup_main) Lookups are supported in v4+ syntax
alsa-lib parser.c:242:(error_node) UCM is not supported for this HDA model (HD-Audio Generic at 0xfcc00000 irq 192)
alsa-lib main.c:1402:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -6
Found hardware: "HDA-Intel" "Realtek ALC1220" "HDA:10ec1220,1458a0c3,00100101" "0x1458" "0xa0c3"
Hardware is initialized using a generic method
```

**Comment by perexg** [comment]
Could you install debug symbols to get the source file and line hints in the trace?

**Comment by mabod** [comment]
How do I install debug symbols?

**Comment by mabod** [comment]
In the meantime I have built 1.2.5 alsactl with debug info

`/usr/bin/alsactl: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=285e21efbc823798683ba916d33f15ff7d8e0652, for GNU/Linux 4.4.0, with debug_info, not stripped`

And it crashed during `alsactl restore`. What shall I provide to you?

**Comment by perexg** [comment]
`gdb --args alsactl restore`, gdb commands `run` and `backtrace` when the code segfaults

**Comment by mabod** [comment]
```
12# gdb --args alsactl restore
GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from alsactl...
(gdb) run
Starting program: /usr/bin/alsactl restore
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
/usr/bin/alsactl: state_lock:129: file /var/lib/alsa/asound.state lock error: Permission denied
/usr/bin/alsactl: load_state:1635: Cannot open /var/lib/alsa/asound.state for reading: Permission denied
alsa-lib ucm_subs.c:252:(rval_lookup_main) Lookups are supported in v4+ syntax
alsa-lib parser.c:242:(error_node) UCM is not supported for this HDA model (HDA ATI HDMI at 0xfcda0000 irq 189)
alsa-lib main.c:1402:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -6
Found hardware: "HDA-Intel" "ATI R6xx HDMI" "HDA:1002aa01,00aa0100,00100700" "0x1002" "0xab38"
Hardware is initialized using a generic method
alsa-lib ucm_subs.c:252:(rval_lookup_main) Lookups are supported in v4+ syntax
alsa-lib parser.c:242:(error_node) UCM is not supported for this HDA model (HD-Audio Generic at 0xfcc00000 irq 191)
alsa-lib main.c:1402:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -6
Found hardware: "HDA-Intel" "Realtek ALC1220" "HDA:10ec1220,1458a0c3,00100101" "0x1458" "0xa0c3"
Hardware is initialized using a generic method
alsa-lib main.c:1402:(snd_use_case_mgr_open) error: failed to import hw:2 use case configuration -2
Found hardware: "USB-Audio" "USB Mixer" "USB0b0e:2476" "" ""
Hardware is initialized using a generic method

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7eda557 in snd_config_delete () from /usr/lib/libasound.so.2
(gdb) backtrace
#0  0x00007ffff7eda557 in snd_config_delete () from /usr/lib/libasound.so.2
#1  0x0000555555560154 in load_state (cfgdir=cfgdir@entry=0x55555556a0ca "/var/lib/alsa", file=0x7fffffffdb60 "\377\377\377\377hw:2", 
    file@entry=0x55555556a0af "/var/lib/alsa/asound.state", initfile=initfile@entry=0x55555556a093 "/usr/share/alsa/init/00main", 
    initflags=initflags@entry=0, cardname=cardname@entry=0x0, do_init=do_init@entry=1) at state.c:1679
#2  0x000055555555a704 in main (argc=<optimized out>, argv=<optimized out>) at alsactl.c:440
(gdb) 
```

**Comment by perexg** [comment]
Thank you. Does this change help?

```
diff --git a/alsactl/state.c b/alsactl/state.c
index 9c75688..439e1f8 100644
--- a/alsactl/state.c
+++ b/alsactl/state.c
@@ -1642,6 +1642,7 @@ int load_state(const char *cfgdir, const char *file,
        snd_config_t *config;
        const char *cardname1;
 
+       config = NULL;
        err = load_configuration(file, &config, &open_failed);
        if (err < 0 && !open_failed)
                return err;
```

**Comment by mabod** [comment]
No. It does not help. Still seg fault.

**Comment by mabod** [comment]
Yes. This does the trick. No seg fault anymore.
